version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html  # Монтируем фронтенд в корень веб-сервера
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge