version: '3.8'

services:
  frontend:
    build: .
    container_name: business-analytics-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - analytics-network

  backend:
    build: ./backend
    container_name: business-analytics-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - analytics-network

networks:
  analytics-network:
    driver: bridge