version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html/src  # Изменено для соответствия nginx.conf
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge