version: '3.8'

services:
  frontend:
    build: .
    container_name: business-analytics-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge